return {
    name = "about",
    args = nil,
    callback = function()
        print("cealshell() 2026 MIT ©")
		print("------------")
		print("developed by janis")
		print("roblox: @the_h0lysandwich")
		print("discord: @_jxnis_")
		print("------------")
		print("discord: cealshell.dev/discord")
    end,
    description = "Credits & Contacts for Cealshell.",
    manual = nil,
    signer = "cealshell",
    alias = nil,
}